package com.aiworkmate.common;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

/**
 * 错误码枚举。
 *
 * <p>每个枚举值只承载 {@code messageKey}，最终展示文案由 {@link org.springframework.context.MessageSource}
 * 按 {@code Accept-Language} 解析；禁止在此硬编码中文文案。
 */
@Getter
@RequiredArgsConstructor
public enum ErrorCode {
    REQUEST_INVALID(40001, "REQUEST_INVALID", HttpStatus.BAD_REQUEST, "error.REQUEST_INVALID"),
    AUTH_REQUIRED(40101, "AUTH_REQUIRED", HttpStatus.UNAUTHORIZED, "error.AUTH_REQUIRED"),
    AUTH_TOKEN_INVALID(40102, "AUTH_TOKEN_INVALID", HttpStatus.UNAUTHORIZED, "error.AUTH_TOKEN_INVALID"),
    AUTH_TOKEN_EXPIRED(40103, "AUTH_TOKEN_EXPIRED", HttpStatus.UNAUTHORIZED, "error.AUTH_TOKEN_EXPIRED"),
    AUTH_CODE_INVALID(40011, "AUTH_CODE_INVALID", HttpStatus.BAD_REQUEST, "error.AUTH_CODE_INVALID"),
    AUTH_CODE_EXPIRED(40012, "AUTH_CODE_EXPIRED", HttpStatus.BAD_REQUEST, "error.AUTH_CODE_EXPIRED"),
    AUTH_CAPTCHA_REQUIRED(40013, "AUTH_CAPTCHA_REQUIRED", HttpStatus.BAD_REQUEST, "error.AUTH_CAPTCHA_REQUIRED"),
    PASSWORD_INCORRECT(40014, "PASSWORD_INCORRECT", HttpStatus.BAD_REQUEST, "error.PASSWORD_INCORRECT"),
    PASSWORD_SAME_AS_OLD(40015, "PASSWORD_SAME_AS_OLD", HttpStatus.BAD_REQUEST, "error.PASSWORD_SAME_AS_OLD"),
    AUTH_ACCOUNT_LOCKED(42301, "AUTH_ACCOUNT_LOCKED", HttpStatus.LOCKED, "error.AUTH_ACCOUNT_LOCKED"),
    PERMISSION_DENIED(40301, "PERMISSION_DENIED", HttpStatus.FORBIDDEN, "error.PERMISSION_DENIED"),
    RESOURCE_FORBIDDEN(40302, "RESOURCE_FORBIDDEN", HttpStatus.FORBIDDEN, "error.RESOURCE_FORBIDDEN"),
    RESOURCE_NOT_FOUND(40401, "RESOURCE_NOT_FOUND", HttpStatus.NOT_FOUND, "error.RESOURCE_NOT_FOUND"),
    APPROVER_NOT_CONFIGURED(42201, "APPROVER_NOT_CONFIGURED", HttpStatus.UNPROCESSABLE_ENTITY,
            "error.APPROVER_NOT_CONFIGURED"),
    BUSINESS_STATE_INVALID(40911, "BUSINESS_STATE_INVALID", HttpStatus.CONFLICT,
            "error.BUSINESS_STATE_INVALID"),
    VERSION_CONFLICT(40912, "VERSION_CONFLICT", HttpStatus.CONFLICT,
            "error.VERSION_CONFLICT"),
    AI_TASK_CONFIRMATION_REQUIRED(40901, "AI_TASK_CONFIRMATION_REQUIRED", HttpStatus.CONFLICT,
            "error.AI_TASK_CONFIRMATION_REQUIRED"),
    INVALID_TASK_STATE(40921, "INVALID_TASK_STATE", HttpStatus.CONFLICT,
            "error.INVALID_TASK_STATE"),
    CONFIRMATION_REQUIRED(40922, "CONFIRMATION_REQUIRED", HttpStatus.CONFLICT,
            "error.CONFIRMATION_REQUIRED"),
    CONFIRMATION_EXPIRED(40923, "CONFIRMATION_EXPIRED", HttpStatus.CONFLICT,
            "error.CONFIRMATION_EXPIRED"),
    GATEWAY_STALE(40924, "GATEWAY_STALE", HttpStatus.CONFLICT,
            "error.GATEWAY_STALE"),
    AI_TASK_CAPABILITY_UNAVAILABLE(50301, "AI_TASK_CAPABILITY_UNAVAILABLE", HttpStatus.SERVICE_UNAVAILABLE,
            "error.AI_TASK_CAPABILITY_UNAVAILABLE"),
    AI_CHAT_UNAVAILABLE(50302, "AI_CHAT_UNAVAILABLE", HttpStatus.SERVICE_UNAVAILABLE,
            "error.AI_CHAT_UNAVAILABLE"),
    EMBEDDING_UNAVAILABLE(50304, "EMBEDDING_UNAVAILABLE", HttpStatus.SERVICE_UNAVAILABLE,
            "error.EMBEDDING_UNAVAILABLE"),
    EMBEDDING_RESPONSE_INVALID(50204, "EMBEDDING_RESPONSE_INVALID", HttpStatus.BAD_GATEWAY,
            "error.EMBEDDING_RESPONSE_INVALID"),
    TOOL_CAPABILITY_UNAVAILABLE(50311, "TOOL_CAPABILITY_UNAVAILABLE", HttpStatus.SERVICE_UNAVAILABLE,
            "error.TOOL_CAPABILITY_UNAVAILABLE"),
    OCR_CAPABILITY_UNAVAILABLE(50312, "OCR_CAPABILITY_UNAVAILABLE", HttpStatus.SERVICE_UNAVAILABLE,
            "error.OCR_CAPABILITY_UNAVAILABLE"),
    RATE_LIMITED(42901, "RATE_LIMITED", HttpStatus.TOO_MANY_REQUESTS, "error.RATE_LIMITED"),
    AUTH_SERVICE_UNAVAILABLE(50303, "AUTH_SERVICE_UNAVAILABLE", HttpStatus.SERVICE_UNAVAILABLE,
            "error.AUTH_SERVICE_UNAVAILABLE"),
    ATTENDANCE_ALREADY_CLOCKED(40913, "ATTENDANCE_ALREADY_CLOCKED", HttpStatus.CONFLICT,
            "error.ATTENDANCE_ALREADY_CLOCKED"),
    ATTENDANCE_RECORD_NOT_FOUND(40402, "ATTENDANCE_RECORD_NOT_FOUND", HttpStatus.NOT_FOUND,
            "error.ATTENDANCE_RECORD_NOT_FOUND"),
    ATTENDANCE_APPROVER_MISSING(42202, "ATTENDANCE_APPROVER_MISSING", HttpStatus.UNPROCESSABLE_ENTITY,
            "error.ATTENDANCE_APPROVER_MISSING"),
    ATTENDANCE_REISSUE_NOT_FOUND(40403, "ATTENDANCE_REISSUE_NOT_FOUND", HttpStatus.NOT_FOUND,
            "error.ATTENDANCE_REISSUE_NOT_FOUND"),
    ATTENDANCE_REISSUE_DECIDED(40914, "ATTENDANCE_REISSUE_DECIDED", HttpStatus.CONFLICT,
            "error.ATTENDANCE_REISSUE_DECIDED"),
    SYSTEM_ERROR(50001, "SYSTEM_ERROR", HttpStatus.INTERNAL_SERVER_ERROR, "error.SYSTEM_ERROR");

    private final int code;
    private final String errorCode;
    private final HttpStatus status;
    private final String messageKey;
}
