import type { ComponentType, CSSProperties } from 'react';
import type { AntdIconProps } from '@ant-design/icons/lib/components/AntdIcon';
import {
  AccountBookOutlined,
  AimOutlined,
  ApartmentOutlined,
  ApiOutlined,
  AuditOutlined,
  BankOutlined,
  BarChartOutlined,
  BellOutlined,
  BookOutlined,
  BugOutlined,
  BulbOutlined,
  CalendarOutlined,
  CheckSquareOutlined,
  CloudOutlined,
  ClusterOutlined,
  CompassOutlined,
  ControlOutlined,
  CopyOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeleteOutlined,
  EditOutlined,
  ExperimentOutlined,
  EyeOutlined,
  FileImageOutlined,
  FileOutlined,
  FileProtectOutlined,
  FileSearchOutlined,
  FileTextOutlined,
  FolderOpenOutlined,
  FolderOutlined,
  FormOutlined,
  FundOutlined,
  GlobalOutlined,
  HeartOutlined,
  HistoryOutlined,
  HomeOutlined,
  IdcardOutlined,
  InboxOutlined,
  LineChartOutlined,
  LinkOutlined,
  LockOutlined,
  LogoutOutlined,
  LeftOutlined,
  MoreOutlined,
  NodeIndexOutlined,
  PaperClipOutlined,
  PieChartOutlined,
  ProfileOutlined,
  QuestionCircleOutlined,
  ReadOutlined,
  ReloadOutlined,
  RightOutlined,
  RobotOutlined,
  RocketOutlined,
  SafetyCertificateOutlined,
  SafetyOutlined,
  SaveOutlined,
  SearchOutlined,
  SendOutlined,
  SettingOutlined,
  ShopOutlined,
  SkinOutlined,
  SnippetsOutlined,
  SolutionOutlined,
  StarOutlined,
  SwapOutlined,
  TableOutlined,
  TagsOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ToolOutlined,
  UploadOutlined,
  WalletOutlined,
} from '@ant-design/icons';
import { IconFont, type IconFontName } from '@/components/IconFont';

const iconFontMap = {
  brand: 'main_icon',
  ai: 'zhinengyouhua',
  csv: 'CSV',
  pdf: 'PDF',
  png: 'PNG',
  jpg: 'JPG',
  txt: 'TXT',
  user: 'yonghuguanli',
  role: 'jiaoseguanli',
  add: 'add_oa',
  pause: 'pause',
  option: 'xuanxiangka',
  export: 'daochu',
  code: 'daimayunhang',
  preview: 'jieguoyulan',
  avatar: 'siyouguize',
  phone: 'shouji',
  email: 'youxiang',
  dashboard: 'dashboard',
  business: 'business',
  platform: 'platform',
  settings: 'settings',
  approval: 'approval',
  hr: 'hr',
  assets: 'assets',
  finance: 'finance',
  integration: 'integration',
  todo: 'todo',
  'leave-application': 'form',
  'my-applications': 'history',
  messages: 'messages',
  form: 'form',
  process: 'process',
  rules: 'rules',
  organization: 'organization',
  'employee-files': 'employee-files',
  attendance: 'attendance',
  'attendance-clock': 'attendance-clock',
  'attendance-exception': 'attendance-exception',
  'attendance-reissue': 'attendance-reissue',
  'attendance-statistics': 'attendance-statistics',
  'employee-change': 'employee-change',
  'asset-ledger': 'asset-ledger',
  'meeting-room': 'meeting-room',
  visitor: 'visitor',
  seal: 'seal',
  expense: 'expense',
  budget: 'budget',
  contracts: 'contracts',
  suppliers: 'suppliers',
  'api-center': 'api-center',
  'page-actions': 'page-actions',
  'runtime-logs': 'runtime-logs',
  sandbox: 'sandbox',
  'access-control': 'access-control',
  'data-permission': 'data-permission',
  audit: 'audit',
  tenant: 'tenant',
  dictionary: 'dictionary',
  help: 'help',
  notification: 'notification',
  appearance: 'appearance',
  logout: 'logout',
  edit: 'edit',
  delete: 'delete',
  upload: 'upload',
  save: 'save',
  search: 'search',
  attachment: 'attachment',
  send: 'send',
  more: 'more',
  copy: 'copy',
  reload: 'reload',
  lock: 'lock',
  history: 'history',
} satisfies Record<string, IconFontName>;

const fallbackIconMap = {
  dashboard: DashboardOutlined,
  business: ApartmentOutlined,
  platform: ApiOutlined,
  settings: SettingOutlined,
  approval: AuditOutlined,
  hr: TeamOutlined,
  assets: InboxOutlined,
  finance: WalletOutlined,
  integration: LinkOutlined,
  todo: CheckSquareOutlined,
  messages: BellOutlined,
  form: FormOutlined,
  process: NodeIndexOutlined,
  rules: SafetyCertificateOutlined,
  organization: ClusterOutlined,
  'employee-files': IdcardOutlined,
  attendance: CalendarOutlined,
  'employee-change': SwapOutlined,
  'asset-ledger': DatabaseOutlined,
  'meeting-room': BankOutlined,
  visitor: TeamOutlined,
  seal: FileProtectOutlined,
  expense: AccountBookOutlined,
  budget: FundOutlined,
  contracts: FileProtectOutlined,
  suppliers: ShopOutlined,
  'api-center': ApiOutlined,
  'page-actions': ControlOutlined,
  'runtime-logs': FileSearchOutlined,
  sandbox: BugOutlined,
  'access-control': SafetyCertificateOutlined,
  'data-permission': DatabaseOutlined,
  audit: AuditOutlined,
  tenant: BankOutlined,
  dictionary: BookOutlined,
  help: QuestionCircleOutlined,
  notification: BellOutlined,
  appearance: SkinOutlined,
  logout: LogoutOutlined,
  edit: EditOutlined,
  delete: DeleteOutlined,
  upload: UploadOutlined,
  save: SaveOutlined,
  search: SearchOutlined,
  attachment: PaperClipOutlined,
  send: SendOutlined,
  more: MoreOutlined,
  copy: CopyOutlined,
  reload: ReloadOutlined,
  lock: LockOutlined,
  history: HistoryOutlined,
  'knowledge-base': DatabaseOutlined,
  previous: LeftOutlined,
  next: RightOutlined,
  aim: AimOutlined,
  'bar-chart': BarChartOutlined,
  book: BookOutlined,
  bulb: BulbOutlined,
  cloud: CloudOutlined,
  compass: CompassOutlined,
  experiment: ExperimentOutlined,
  eye: EyeOutlined,
  'file-image': FileImageOutlined,
  file: FileOutlined,
  'file-text': FileTextOutlined,
  'folder-open': FolderOpenOutlined,
  folder: FolderOutlined,
  global: GlobalOutlined,
  heart: HeartOutlined,
  home: HomeOutlined,
  'line-chart': LineChartOutlined,
  'pie-chart': PieChartOutlined,
  profile: ProfileOutlined,
  read: ReadOutlined,
  robot: RobotOutlined,
  rocket: RocketOutlined,
  safety: SafetyOutlined,
  snippets: SnippetsOutlined,
  solution: SolutionOutlined,
  star: StarOutlined,
  table: TableOutlined,
  tags: TagsOutlined,
  thunderbolt: ThunderboltOutlined,
  tool: ToolOutlined,
} satisfies Record<string, ComponentType<AntdIconProps>>;

export type OaIconName = keyof typeof iconFontMap | keyof typeof fallbackIconMap;

export const oaKnowledgeBaseIconOptions: Array<{ value: OaIconName; labelKey: string }> = [
  { value: 'knowledge-base', labelKey: 'oa.iconLabel.knowledge-base' },
  { value: 'book', labelKey: 'oa.iconLabel.book' },
  { value: 'read', labelKey: 'oa.iconLabel.read' },
  { value: 'file', labelKey: 'oa.iconLabel.file' },
  { value: 'file-text', labelKey: 'oa.iconLabel.file-text' },
  { value: 'file-image', labelKey: 'oa.iconLabel.file-image' },
  { value: 'folder', labelKey: 'oa.iconLabel.folder' },
  { value: 'folder-open', labelKey: 'oa.iconLabel.folder-open' },
  { value: 'profile', labelKey: 'oa.iconLabel.profile' },
  { value: 'snippets', labelKey: 'oa.iconLabel.snippets' },
  { value: 'tags', labelKey: 'oa.iconLabel.tags' },
  { value: 'star', labelKey: 'oa.iconLabel.star' },
  { value: 'cloud', labelKey: 'oa.iconLabel.cloud' },
  { value: 'global', labelKey: 'oa.iconLabel.global' },
  { value: 'compass', labelKey: 'oa.iconLabel.compass' },
  { value: 'bulb', labelKey: 'oa.iconLabel.bulb' },
  { value: 'experiment', labelKey: 'oa.iconLabel.experiment' },
  { value: 'table', labelKey: 'oa.iconLabel.table' },
  { value: 'bar-chart', labelKey: 'oa.iconLabel.bar-chart' },
  { value: 'pie-chart', labelKey: 'oa.iconLabel.pie-chart' },
  { value: 'line-chart', labelKey: 'oa.iconLabel.line-chart' },
  { value: 'robot', labelKey: 'oa.iconLabel.robot' },
  { value: 'thunderbolt', labelKey: 'oa.iconLabel.thunderbolt' },
  { value: 'aim', labelKey: 'oa.iconLabel.aim' },
  { value: 'eye', labelKey: 'oa.iconLabel.eye' },
  { value: 'tool', labelKey: 'oa.iconLabel.tool' },
  { value: 'rocket', labelKey: 'oa.iconLabel.rocket' },
  { value: 'solution', labelKey: 'oa.iconLabel.solution' },
  { value: 'safety', labelKey: 'oa.iconLabel.safety' },
  { value: 'home', labelKey: 'oa.iconLabel.home' },
  { value: 'heart', labelKey: 'oa.iconLabel.heart' },
  { value: 'dashboard', labelKey: 'oa.iconLabel.dashboard' },
  { value: 'form', labelKey: 'oa.iconLabel.form' },
  { value: 'audit', labelKey: 'oa.iconLabel.audit' },
  { value: 'help', labelKey: 'oa.iconLabel.help' },
  { value: 'organization', labelKey: 'oa.iconLabel.organization' },
];

export const oaMenuIconOptions: Array<{ value: OaIconName; labelKey: string }> = [
  { value: 'dashboard', labelKey: 'oa.iconLabel.dashboard' },
  { value: 'ai', labelKey: 'oa.iconLabel.ai' },
  { value: 'business', labelKey: 'oa.iconLabel.business' },
  { value: 'platform', labelKey: 'oa.iconLabel.platform' },
  { value: 'settings', labelKey: 'oa.iconLabel.settings' },
  { value: 'approval', labelKey: 'oa.iconLabel.approval' },
  { value: 'hr', labelKey: 'oa.iconLabel.hr' },
  { value: 'assets', labelKey: 'oa.iconLabel.assets' },
  { value: 'finance', labelKey: 'oa.iconLabel.finance' },
  { value: 'integration', labelKey: 'oa.iconLabel.integration' },
  { value: 'todo', labelKey: 'oa.iconLabel.todo' },
  { value: 'messages', labelKey: 'oa.iconLabel.messages' },
  { value: 'form', labelKey: 'oa.iconLabel.form' },
  { value: 'process', labelKey: 'oa.iconLabel.process' },
  { value: 'rules', labelKey: 'oa.iconLabel.rules' },
  { value: 'organization', labelKey: 'oa.iconLabel.organizationStructure' },
  { value: 'attendance-clock', labelKey: 'oa.iconLabel.attendance-clock' },
  { value: 'attendance-exception', labelKey: 'oa.iconLabel.attendance-exception' },
  { value: 'attendance-reissue', labelKey: 'oa.iconLabel.attendance-reissue' },
  { value: 'attendance-statistics', labelKey: 'oa.iconLabel.attendance-statistics' },
  { value: 'user', labelKey: 'oa.iconLabel.user' },
  { value: 'role', labelKey: 'oa.iconLabel.role' },
  { value: 'access-control', labelKey: 'oa.iconLabel.access-control' },
  { value: 'data-permission', labelKey: 'oa.iconLabel.data-permission' },
  { value: 'audit', labelKey: 'oa.iconLabel.audit' },
  { value: 'tenant', labelKey: 'oa.iconLabel.tenant' },
  { value: 'dictionary', labelKey: 'oa.iconLabel.dictionary' },
];

const configuredIconAliases: Record<string, OaIconName> = {
  DashboardOutlined: 'dashboard',
  ApartmentOutlined: 'business',
  ApiOutlined: 'platform',
  SettingOutlined: 'settings',
  RobotOutlined: 'ai',
};

const routeIconMap: Record<string, OaIconName> = {
  workspace: 'dashboard',
  dashboard: 'dashboard',
  'ai-workspace': 'ai',
  todo: 'todo',
  'leave-application': 'form',
  'my-applications': 'history',
  messages: 'messages',
  business: 'business',
  approval: 'approval',
  'approval-list': 'approval',
  'approval-start': 'send',
  'approval-form': 'edit',
  'form-engine': 'form',
  'process-config': 'process',
  'process-manage': 'tool',
  'approval-rules': 'rules',
  hr: 'hr',
  'org-tree': 'organization',
  'employee-files': 'employee-files',
  attendance: 'attendance',
  'attendance-clock': 'attendance-clock',
  'attendance-exception': 'attendance-exception',
  'attendance-reissue': 'attendance-reissue',
  'attendance-statistics': 'attendance-statistics',
  'employee-change': 'employee-change',
  assets: 'assets',
  'asset-ledger': 'asset-ledger',
  'meeting-room': 'meeting-room',
  'visitor-booking': 'visitor',
  'seal-usage': 'seal',
  finance: 'finance',
  expense: 'expense',
  budget: 'budget',
  contracts: 'contracts',
  suppliers: 'suppliers',
  platform: 'platform',
  integration: 'integration',
  'api-center': 'api-center',
  'page-actions': 'page-actions',
  'runtime-logs': 'runtime-logs',
  'sandbox-replay': 'sandbox',
  settings: 'settings',
  'access-control': 'role',
  'data-permission': 'data-permission',
  'ai-permission': 'ai',
  'audit-center': 'audit',
  'tenant-config': 'tenant',
  dictionary: 'dictionary',
  'knowledge-base': 'knowledge-base',
};

export interface OaIconProps {
  name: OaIconName;
  size?: CSSProperties['width'];
  className?: string;
  style?: CSSProperties;
  title?: string;
}

export function OaIcon({
  name,
  size = '1em',
  className,
  style,
  title,
}: OaIconProps) {
  const iconFontName = iconFontMap[name as keyof typeof iconFontMap];
  if (iconFontName) {
    return (
      <IconFont
        name={iconFontName}
        size={size}
        className={className}
        style={style}
        title={title}
      />
    );
  }

  const FallbackIcon = fallbackIconMap[name as keyof typeof fallbackIconMap];
  if (!FallbackIcon) return null;

  return (
    <FallbackIcon
      className={className}
      aria-hidden={title ? undefined : true}
      aria-label={title}
      role={title ? 'img' : undefined}
      style={{
        fontSize: size,
        ...style,
      }}
    />
  );
}

export function resolveOaMenuIcon(
  routeId: string,
  configuredIcon?: string,
): OaIconName | undefined {
  const configuredName = configuredIcon
    ? configuredIconAliases[configuredIcon]
      || (
        configuredIcon in iconFontMap || configuredIcon in fallbackIconMap
          ? configuredIcon as OaIconName
          : undefined
      )
    : undefined;
  return configuredName || routeIconMap[routeId];
}
