INSERT INTO agent_tool (
    tenant_id, code, name, description, handler_version,
    parameters_schema, output_schema, schema_hash, risk_level,
    required_permissions, permission_mode, data_scope_policy,
    retry_policy, side_effect, confirmation_policy,
    max_result_items, max_result_bytes, timeout_ms, audit_level, enabled
) VALUES (
    NULL,
    'leave.apply',
    'Apply for leave',
    'Atomically creates and submits exactly one leave application owned by the authenticated user.',
    '1.0.0',
    '{"type":"object","additionalProperties":false,"required":["leaveType","startDate","startPeriod","endDate","endPeriod","reason"],"properties":{"leaveType":{"type":"string","enum":["ANNUAL","PERSONAL","SICK","MARRIAGE","MATERNITY","PATERNITY","BEREAVEMENT","COMPENSATORY","OTHER"]},"approverUserId":{"type":"integer","minimum":1},"startDate":{"type":"string","format":"date","maxLength":10},"startPeriod":{"type":"string","enum":["AM","PM"]},"endDate":{"type":"string","format":"date","maxLength":10},"endPeriod":{"type":"string","enum":["AM","PM"]},"reason":{"type":"string","minLength":1,"maxLength":500}}}'::jsonb,
    '{"type":"object","additionalProperties":false,"required":["applicationId","status","version","approvalTaskId"],"properties":{"applicationId":{"type":"integer","minimum":1},"status":{"type":"string","const":"PENDING"},"version":{"type":"integer","minimum":1},"approvalTaskId":{"type":"integer","minimum":1}}}'::jsonb,
    'sha256:f782725f4e4118589935e376af2423db78401d04ed6a355c6f4b32d51176dcd8',
    'L2',
    '["leave:create"]'::jsonb,
    'ALL',
    'SELF',
    'NEVER',
    'SINGLE_WRITE',
    'SECONDARY',
    1,
    16384,
    15000,
    'FULL_WRITE_AUDIT',
    TRUE
)
ON CONFLICT (code) WHERE tenant_id IS NULL DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    handler_version = EXCLUDED.handler_version,
    parameters_schema = EXCLUDED.parameters_schema,
    output_schema = EXCLUDED.output_schema,
    schema_hash = EXCLUDED.schema_hash,
    risk_level = EXCLUDED.risk_level,
    required_permissions = EXCLUDED.required_permissions,
    permission_mode = EXCLUDED.permission_mode,
    data_scope_policy = EXCLUDED.data_scope_policy,
    retry_policy = EXCLUDED.retry_policy,
    side_effect = EXCLUDED.side_effect,
    confirmation_policy = EXCLUDED.confirmation_policy,
    max_result_items = EXCLUDED.max_result_items,
    max_result_bytes = EXCLUDED.max_result_bytes,
    timeout_ms = EXCLUDED.timeout_ms,
    audit_level = EXCLUDED.audit_level,
    enabled = EXCLUDED.enabled,
    updated_at = CURRENT_TIMESTAMP;
