INSERT INTO agent_tool (
    tenant_id, code, name, description, handler_version,
    parameters_schema, output_schema, schema_hash, risk_level,
    required_permissions, permission_mode, data_scope_policy,
    retry_policy, side_effect, confirmation_policy,
    max_result_items, max_result_bytes, timeout_ms, audit_level, enabled
) VALUES (
    NULL,
    'leave.submit',
    'Submit my existing leave draft',
    'Submits one pre-existing draft owned by the authenticated user in the authenticated tenant.',
    '1.0.0',
    '{"type":"object","additionalProperties":false,"required":["applicationId","version"],"properties":{"applicationId":{"type":"integer","minimum":1},"version":{"type":"integer","minimum":0}}}'::jsonb,
    '{"type":"object","additionalProperties":false,"required":["applicationId","status","version"],"properties":{"applicationId":{"type":"integer","minimum":1},"status":{"type":"string","const":"PENDING"},"version":{"type":"integer","minimum":1}}}'::jsonb,
    'sha256:b35875584e04f55f8da0b5448d32c5e89e11c32df78e6bdc2d2c2ccd11f0dce3',
    'L2',
    '["leave:create"]'::jsonb,
    'ALL',
    'SELF',
    'NEVER',
    'SINGLE_WRITE',
    'SECONDARY',
    1,
    16384,
    15000,
    'FULL_WRITE_AUDIT',
    TRUE
)
ON CONFLICT (code) WHERE tenant_id IS NULL DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    handler_version = EXCLUDED.handler_version,
    parameters_schema = EXCLUDED.parameters_schema,
    output_schema = EXCLUDED.output_schema,
    schema_hash = EXCLUDED.schema_hash,
    risk_level = EXCLUDED.risk_level,
    required_permissions = EXCLUDED.required_permissions,
    permission_mode = EXCLUDED.permission_mode,
    data_scope_policy = EXCLUDED.data_scope_policy,
    retry_policy = EXCLUDED.retry_policy,
    side_effect = EXCLUDED.side_effect,
    confirmation_policy = EXCLUDED.confirmation_policy,
    max_result_items = EXCLUDED.max_result_items,
    max_result_bytes = EXCLUDED.max_result_bytes,
    timeout_ms = EXCLUDED.timeout_ms,
    audit_level = EXCLUDED.audit_level,
    enabled = EXCLUDED.enabled,
    updated_at = CURRENT_TIMESTAMP;
