'use client';
import { useCallback,useEffect,useState } from 'react';
import { Alert,App,Badge,Button,Card,Col,Descriptions,Drawer,Empty,Form,Input,Row,Select,Space,Statistic,Tag,Timeline,Typography } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { useTranslation } from 'react-i18next';
import { OaIcon } from '@/components/OaIcon';
import ResponsiveTable from './ResponsiveTable';
import { integrationApi,type EndpointPayload,type EndpointStatus,type IntegrationEndpoint,type IntegrationInvocation } from '@/lib/integrationApi';
import { formatOaApiError } from '@/lib/oaApi';
import { message } from '@/lib/antdMessage';

const statuses:EndpointStatus[]=['DRAFT','ACTIVE','DISABLED']; const methods=['GET','POST','PUT','PATCH','DELETE'];
const statusColors:Record<string,string>={DRAFT:'default',ACTIVE:'green',DISABLED:'orange',SUCCESS:'green',FAILED:'red'};
export default function ApiCenterPage(){
 const {t,i18n}=useTranslation();const {modal}=App.useApp();const [form]=Form.useForm<EndpointPayload>();
 const [records,setRecords]=useState<IntegrationEndpoint[]>([]);const [stats,setStats]=useState({total:0,active:0,disabled:0,successful:0,failed:0});const [total,setTotal]=useState(0);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [canManage,setCanManage]=useState(false);
 const [keyword,setKeyword]=useState('');const [status,setStatus]=useState<EndpointStatus>();const [page,setPage]=useState(1);const [size,setSize]=useState(20);const [editor,setEditor]=useState(false);const [editing,setEditing]=useState<IntegrationEndpoint>();const [upstreams,setUpstreams]=useState<{code:string;label:string;available:boolean}[]>([]);const [detail,setDetail]=useState<{endpoint:IntegrationEndpoint;invocations:IntegrationInvocation[]}>();const [detailOpen,setDetailOpen]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const r=await integrationApi.list({keyword,status,page,size});setRecords(r.records);setStats(r.stats);setTotal(r.total);setCanManage(r.canManage)}catch(e){message.error(formatOaApiError(e))}finally{setLoading(false)}},[keyword,status,page,size]);useEffect(()=>{void load()},[load]);
 const loadOptions=async()=>{const r=await integrationApi.options();setUpstreams(r.upstreams);return r.upstreams};
 const openCreate=async()=>{try{await loadOptions();setEditing(undefined);form.resetFields();form.setFieldsValue({method:'GET'});setEditor(true)}catch(e){message.error(formatOaApiError(e))}};
 const openEdit=async(e:IntegrationEndpoint)=>{try{await loadOptions();setEditing(e);form.setFieldsValue({...e});setEditor(true)}catch(err){message.error(formatOaApiError(err))}};
 const save=async()=>{try{const value=await form.validateFields();setSaving(true);editing?await integrationApi.update(editing.id,{...value,version:editing.version}):await integrationApi.create(value);message.success(t('apiCenter.messages.saved'));setEditor(false);await load()}catch(e){if(e instanceof Error)message.error(formatOaApiError(e))}finally{setSaving(false)}};
 const showDetail=async(id:number)=>{try{setDetail(await integrationApi.detail(id));setDetailOpen(true)}catch(e){message.error(formatOaApiError(e))}};
 const changeStatus=(endpoint:IntegrationEndpoint,target:EndpointStatus)=>modal.confirm({title:t('apiCenter.actions.confirmStatus'),content:t(`apiCenter.status.${target}`),onOk:async()=>{try{await integrationApi.status(endpoint.id,target,endpoint.version);message.success(t('apiCenter.messages.status'));await load();if(detailOpen)setDetail(await integrationApi.detail(endpoint.id))}catch(e){message.error(formatOaApiError(e))}}});
 const execute=(endpoint:IntegrationEndpoint)=>modal.confirm({title:t('apiCenter.actions.confirmExecute'),content:t('apiCenter.actions.executeHint',{name:endpoint.name}),okText:t('apiCenter.actions.execute'),onOk:async()=>{try{const result=await integrationApi.execute(endpoint.id,endpoint.version);result.outcome==='SUCCESS'?message.success(t('apiCenter.messages.success')):message.error(t('apiCenter.messages.failed',{code:result.errorCode??'-'}));await load();if(detailOpen)setDetail(await integrationApi.detail(endpoint.id))}catch(e){message.error(formatOaApiError(e))}}});
 const columns:ColumnsType<IntegrationEndpoint>=[
  {title:t('apiCenter.columns.endpoint'),key:'endpoint',render:(_,e)=><Space direction="vertical" size={0}><Button type="link" onClick={()=>void showDetail(e.id)}>{e.name}</Button><Typography.Text type="secondary">{e.code}</Typography.Text></Space>},
  {title:t('apiCenter.columns.method'),dataIndex:'method',render:v=><Tag color={v==='GET'?'blue':v==='DELETE'?'red':'gold'}>{v}</Tag>},
  {title:t('apiCenter.columns.path'),key:'path',render:(_,e)=><Typography.Text code>{e.upstreamCode}{e.relativePath}</Typography.Text>},
  {title:t('apiCenter.columns.status'),dataIndex:'status',render:v=><Badge status={v==='ACTIVE'?'success':v==='DISABLED'?'warning':'default'} text={t(`apiCenter.status.${v}`)}/>},
  {title:t('apiCenter.columns.updatedAt'),dataIndex:'updatedAt',render:v=>new Date(v).toLocaleString(i18n.language)},
  {title:t('common.actions'),key:'actions',fixed:'right',render:(_,e)=><Space wrap><Button size="small" onClick={()=>void showDetail(e.id)}>{t('common.view')}</Button>{e.canManage&&e.status!=='ACTIVE'&&<Button size="small" onClick={()=>void openEdit(e)}>{t('common.edit')}</Button>}{e.canExecute&&<Button type="primary" size="small" icon={<OaIcon name="send"/>} onClick={()=>execute(e)}>{t('apiCenter.actions.execute')}</Button>}</Space>}
 ];
 return <section className="oa-api-center-page"><header className="oa-api-center-hero"><div className="oa-api-center-title"><span className="oa-api-center-pulse"><OaIcon name="api-center" size={26}/></span><div><Typography.Text className="oa-api-center-eyebrow">{t('apiCenter.eyebrow')}</Typography.Text><Typography.Title level={2}>{t('apiCenter.title')}</Typography.Title><Typography.Paragraph>{t('apiCenter.subtitle')}</Typography.Paragraph></div></div><Space direction="vertical" align="end"><Tag icon={<OaIcon name="lock"/>} color="blue">{t('apiCenter.gatewayBadge')}</Tag>{canManage&&<Button type="primary" onClick={()=>void openCreate()} icon={<OaIcon name="add"/>}>{t('apiCenter.actions.create')}</Button>}</Space></header>
 <Row gutter={[12,12]}>{(['total','active','successful','failed'] as const).map(key=><Col xs={12} lg={6} key={key}><Card><Statistic title={t(`apiCenter.stats.${key}`)} value={stats[key]} valueStyle={key==='failed'&&stats.failed?{color:'var(--oa-danger)'}:undefined}/></Card></Col>)}</Row>
 <Card className="oa-api-center-list"><div className="oa-api-center-toolbar"><Input.Search allowClear placeholder={t('apiCenter.filters.keyword')} onSearch={v=>{setKeyword(v);setPage(1)}}/><Select allowClear placeholder={t('apiCenter.filters.status')} options={statuses.map(v=>({value:v,label:t(`apiCenter.status.${v}`)}))} onChange={v=>{setStatus(v);setPage(1)}}/><Button onClick={()=>void load()}>{t('common.refresh')}</Button></div><ResponsiveTable rowKey="id" columns={columns} dataSource={records} loading={loading} pagination={{current:page,pageSize:size,total,showSizeChanger:true,onChange:(p,s)=>{setPage(p);setSize(s)}}}/></Card>
 <Drawer open={editor} onClose={()=>setEditor(false)} title={t(editing?'apiCenter.editor.edit':'apiCenter.editor.create')} width={600} extra={<Button type="primary" loading={saving} onClick={()=>void save()}>{t('common.save')}</Button>}><Alert type="info" showIcon message={t('apiCenter.editor.securityTitle')} description={t('apiCenter.editor.securityHint')}/><Form form={form} layout="vertical" className="oa-api-center-form"><Row gutter={12}><Col span={12}><Form.Item name="code" label={t('apiCenter.fields.code')} rules={[{required:true}]}><Input disabled={!!editing}/></Form.Item></Col><Col span={12}><Form.Item name="name" label={t('apiCenter.fields.name')} rules={[{required:true}]}><Input/></Form.Item></Col></Row><Form.Item name="upstreamCode" label={t('apiCenter.fields.upstream')} rules={[{required:true}]}><Select options={upstreams.map(u=>({value:u.code,label:<Space>{u.label}<Tag color={u.available?'green':'default'}>{t(u.available?'apiCenter.upstream.available':'apiCenter.upstream.unavailable')}</Tag></Space>,disabled:!u.available}))}/></Form.Item><Row gutter={12}><Col span={7}><Form.Item name="method" label={t('apiCenter.fields.method')} rules={[{required:true}]}><Select options={methods.map(v=>({value:v,label:v}))}/></Form.Item></Col><Col span={17}><Form.Item name="relativePath" label={t('apiCenter.fields.path')} rules={[{required:true}]}><Input placeholder="/v1/health"/></Form.Item></Col></Row><Form.Item noStyle shouldUpdate={(a,b)=>a.method!==b.method}>{({getFieldValue})=>!['GET','DELETE'].includes(getFieldValue('method'))&&<Form.Item name="requestTemplate" label={t('apiCenter.fields.template')}><Input.TextArea rows={8} className="oa-api-center-code" placeholder={'{\n  "sample": "value"\n}'}/></Form.Item>}</Form.Item><Form.Item name="description" label={t('apiCenter.fields.description')}><Input.TextArea rows={3}/></Form.Item></Form></Drawer>
 <Drawer open={detailOpen} onClose={()=>setDetailOpen(false)} title={t('apiCenter.detail.title')} width={720}>{detail?<><Descriptions column={2} items={[{key:'code',label:t('apiCenter.fields.code'),children:detail.endpoint.code},{key:'upstream',label:t('apiCenter.fields.upstream'),children:detail.endpoint.upstreamCode},{key:'method',label:t('apiCenter.fields.method'),children:<Tag>{detail.endpoint.method}</Tag>},{key:'path',label:t('apiCenter.fields.path'),children:<Typography.Text code>{detail.endpoint.relativePath}</Typography.Text>}]}/><Space wrap className="oa-api-center-status-actions">{detail.endpoint.allowedTransitions.map(s=><Button key={s} onClick={()=>changeStatus(detail.endpoint,s)}>{t(`apiCenter.status.${s}`)}</Button>)}{detail.endpoint.canExecute&&<Button type="primary" onClick={()=>execute(detail.endpoint)}>{t('apiCenter.actions.execute')}</Button>}</Space><Typography.Title level={5}>{t('apiCenter.detail.history')}</Typography.Title>{detail.invocations.length?<Timeline items={detail.invocations.map(x=>({color:x.outcome==='SUCCESS'?'green':'red',children:<div className="oa-api-center-run"><Space><Tag color={statusColors[x.outcome]}>{t(`apiCenter.outcome.${x.outcome}`)}</Tag>{x.httpStatus&&<Tag>HTTP {x.httpStatus}</Tag>}<Typography.Text type="secondary">{x.durationMs} ms</Typography.Text></Space><div>{x.operatorLabel} · {new Date(x.createdAt).toLocaleString(i18n.language)}</div>{x.errorCode&&<Alert type="error" message={t(`apiCenter.errors.${x.errorCode}`,{defaultValue:x.errorCode})}/>} {x.responsePreview&&<Typography.Paragraph><pre>{x.responsePreview}</pre></Typography.Paragraph>}</div>}))}/>:<Empty description={t('apiCenter.detail.empty')}/>}</>:<Empty/>}</Drawer>
 </section>;
}
