package com.aiworkmate.agent.gateway;

public enum GatewayDecisionCode {
    ALLOWED,
    GATEWAY_DISABLED,
    GATEWAY_DENIED,
    GATEWAY_STALE,
    GATEWAY_THROTTLED,
    GATEWAY_UNAVAILABLE,
    TOOL_INPUT_REJECTED,
    TOOL_ACCESS_REJECTED,
    TOOL_RESOURCE_NOT_FOUND,
    TOOL_STATE_CONFLICT,
    TOOL_RESULT_UNKNOWN,
    TOOL_RESULT_INVALID
}
